Algoritmo "atividade 2 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Atividade 2 (dimensões de um quadrado e calcular área
// Autor(a)    : Thays
// Data atual  : 23/02/2024
Var
altura:real
area:real

Inicio
// ATIVIDADE2
// UM ALGORITMO PARA LER AS DIMENSÕES DE UM QUADRADO E CALCULAR A ÁREA

escreva("Altura? ")
leia(altura)
area <- altura * altura
escreva("area do quadrado é: ", area:0:2, " metros ao quadrado")

Fimalgoritmo